---
# comment as a test22
- name: create user
  hosts: testcloud
  remote_user: naser
  become: yes
  gather_facts: no
  tasks:
    - name: create new user
      user:
        name: jeff
        shell: /bin/bash
        groups: 
          - sudo
        append: yes
        password: '$6$5jJ/4Vr6/ZGzu$oTCX8vyA5VxeoM1g38qjWQAql.2NXNEvgl6Vw3POk3aYfOpfD0SBdIJywULf4L49VbysYeemPcTMiXQgPYUTP1'
    - name: Set authorized key taken from file
      authorized_key:
        user: jeff
        state: present
        key: "{{ lookup('file', '/home/naser/Desktop/id_rsa.pub') }}"  
